#!/bin/bash

name=$(jq -r '.name' data.json | sed 's/.*/\u&/')
type=$(jq -r '.types[0].type.name' data.json | sed 's/.*/\u&/')
weight=$(jq -r '.weight' data.json)
height=$(jq -r '.height' data.json)

formatted_weight=$(awk "BEGIN {printf \"%.0f\", $weight/10}")
formatted_height=$(awk "BEGIN {printf \"%.1f\", $height/10}")

echo "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."
